name: Autotag and Release
on: push
    # branches:
    #   - main
    env:
      GH_TOKEN: ${{ github.token }}
jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make tag-release
        env:
          GH_TOKEN: ${{ github.token }}
