name: Validate Test README
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: lint & test
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: ./
        with:
          filepath: ${{ github.workspace }}/fixtures/good.md
      - name: Shellcheck Lint
        run: make lint
      - name: Test "Bad" cases are rejected
        run: make test
  